services:
  frontend:
    container_name: lrar_frontend
    build: ./frontend
    ports:
      - "5173:80"
    networks:
      - app-network

  backend:
    container_name: lrar_backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3001:3001"
    networks:
      - app-network


networks:
  app-network:
