version: '3.8'

services:
  frontend:
    container_name: lrar_frontend
    build: ./frontend
    ports:
      - "5173:80"
    networks:
      - app-network

  backend:
    container_name: lrar_backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: lrar_database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:${POSTGRES_PORT}"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 5

  diesel:
    container_name: lrar_diesel_orm
    build:
      context: .
      dockerfile: diesel/Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - .:/diesel
    command: sleep infinity

volumes:
  db-data:

networks:
  app-network:
